version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/code
    links:
      - mongo:some-development-mongo-host
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
